esphome:
  name: pir_sensor_2
  platform: ESP32
  board: esp32doit-devkit-v1

binary_sensor:
  - platform: gpio
    name: "PIR Sensor"
    device_class: motion
    pin: GPIO02

wifi:
  ssid: "SMARTSM"
  password: "Hadescyber2010"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pir Sensor 2 Fallback Hotspot"
    password: "iTTH0SywzwxI"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
